env:
  browser: true
  es6: true
extends:
  - "airbnb-base"
  - "plugin:prettier/recommended"
globals:
  process: true
plugins:
  - prettier
rules:
  camelcase: 1
  no-param-reassign: ["error", { "props": false }]
  quotes: ["error", "single"]
  no-use-before-define: ["error", { "functions": false }]
  prettier/prettier:
    [
      "error",
      {
        "singleQuote": true,
        "bracketSpacing": true,
        "jsxBracketSameLine": true,
      },
    ]
